version: '3.1'
services:
  API:
    image: 'service-visits.jar'
    ports:
      - "8080:8080"
    depends_on:
      - postgresDb:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/servicetracker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresDb:
    image: postgres
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=servicetracker
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
